version: '3.8'
services:
    db:
        image: postgres:15-alpine
        restart: unless-stopped
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            -   "5432"

    directus:
        image: directus/directus:11.5.1
        ports:
            - 8055:8055
        volumes:
            - ./uploads:/directus/uploads
            - ./extensions:/directus/extensions
        environment:
            SECRET: ${DIRECTUS_SECRET}
            ADMIN_EMAIL: ${ADMIN_EMAIL}
            ADMIN_PASSWORD: ${ADMIN_PASSWORD}
            DB_CLIENT: "pg"
            DB_HOST: db
            DB_PORT: 5432
            DB_USER: ${POSTGRES_USER}
            DB_PASSWORD: ${POSTGRES_PASSWORD}
            DB_DATABASE: ${POSTGRES_DB}
            WEBSOCKETS_ENABLED: "true"
        depends_on:
            - db

volumes:
    db_data:

